___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [6]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [7]:
#in cmd : pip list  gives out the list of packeges and its version
np. __version__


'1.24.1'

Створити вектор з 10 елементів, заповнений одиницями:

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [11]:
vector2=np.arange(0,11)
vector2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [ ]:
np.matrix('0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0; 0 0 0 0 0')

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [17]:
import numpy as np
r=np.random.randint(-10,10,20)
print(r)
count=[]
for i in range(20):
    if r[i]!=0:
        count=count+[i]
print("Indexes of non-zero entries:",count)

[-1  0  9 -2  8 -5  2  8 -4  1  1 -3  9 -3 -1  8 -6 -2 -2  0]
Indexes of non-zero entries: [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [20]:
import statistics as stat
stat.mean(r)
stat.median(r)
stat.variance(r)

np.mean(r)
np.median(r)
np.std(r)

4.767336782733102

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [28]:
import numpy as np
#m4na2=np.random.randint(10,size=(4,2))
#m2na2=np.random.randint(10,size=(2,2))
m4na2=np.random.random((4,2))
m2na2=np.random.random((2,2))
#matrix product
print(np.dot(m4na2,m2na2))
print(m4na2@m2na2)

[[0.42756412 0.18413999]
 [0.45983752 0.58577883]
 [0.47351309 0.59044736]
 [0.22053045 0.53708586]]
[[0.42756412 0.18413999]
 [0.45983752 0.58577883]
 [0.47351309 0.59044736]
 [0.22053045 0.53708586]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [37]:
m4na2=np.random.randint(10,size=(4,2))
m2na2=np.random.randint(10,size=(2,2))
M = np.dot(m4na2,m2na2)
arr = M.flatten()
print("Matrix: ",M)
print("Flattened matrix: ",arr)
max=np.max(M)
min=np.min(M)
print("Max number",max,"Min number",min)

ind = (np.where((arr == min) | ((arr == max))))
for i in ind:
    arr[i] = 0
#vector04[ind[1]] = 0
arr

Matrix:  [[54 45]
 [20 24]
 [76 66]
 [94 93]]
Flattened matrix:  [54 45 20 24 76 66 94 93]
Max number 94 Min number 20


array([54, 45,  0, 24, 76, 66,  0, 93])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [45]:
for i in range(1, 4):
    print(np.correlate(M[0], M[i]))

[2160]
[7074]
[9261]


Дано матрицю. Знайти ранг матриці:

In [46]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
print("Rank of matrix: ",np.linalg.matrix_rank(a))



Rank of matrix:  3


Знайти визначник матриці:

In [47]:
s=np.linalg.det(a)
print("Determinant: %.2f" % s)

Determinant: 440.00


Знайти власні значення та власні вектори матриці: 

In [48]:
import numpy as np
from numpy.linalg import eig
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

w,v=eig(a)
print('E-value:', w)
print('E-vector', v)

E-value: [14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j]
E-vector [[ 0.43131913+0.j          0.31386258+0.47450898j  0.31386258-0.47450898j]
 [ 0.41502436+0.j          0.07049527-0.4090732j   0.07049527+0.4090732j ]
 [ 0.8010734 +0.j         -0.7099444 +0.j         -0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [53]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())


a = np.random.randint(0,10,50)
uniq, count = np.unique(a, return_counts = True)
print (uniq[uniq == np.max(count)])

[3 9 6 8 3 2 4 9 8 0 8 1 5 4 0 8 0 9 1 3 2 3 3 6 9 0 0 4 6 5 4 4 4 9 1 1 5
 9 0 3 8 4 2 4 1 8 5 4 4 0]
4
[7]


Виведіть лише парні числа, що діляться на 5:

In [54]:
a = np.random.randint(0,51,50)
for i in a:
    if i%10==0:
        print(i)


10
0
0
30
20


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [38]:
import numpy as np
m_list=[[2,5],[1,-10]]
A=np.array(m_list)
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)
B=np.array([1,3])
X=np.linalg.inv(A).dot(B)
print(X)

[[  2   5]
 [  1 -10]]
[[ 0.4   0.2 ]
 [ 0.04 -0.08]]
[ 1.  -0.2]
